Infinite recursive loop issue fixed
cloudcogsio/omnipay-firstatlanticcommerce-gateway pull request #4
Opened 2024-06-06 09:29 UTC by jeet1293

Infinite recursive loop issue fixed

2024-11-06 13:13 UTC, jeet1293 commented
hello @cloudcogsio, can you please review this PR and merge if it looks good to you?

2024-11-07 03:50 UTC, cloudcogsio commented
> hello @cloudcogsio, can you please review this PR and merge if it looks good to you?

Hi, can you write up the issue you encountered along with how I can reproduce so I can easily check and confirm? Thanks.

2024-11-08 11:27 UTC, jeet1293 commented
don’t have a code sample to share, but I can explain what I was working on when I encountered this issue (June 2024).

I was building a Laravel 8 application and had integrated your package into it. I tried both code snippets provided in your README file, but neither returned a response. After reviewing your code, I removed one specific line, and then I was able to get a response.

1. **Generate a new Laravel 8 project**:

    ```bash
    composer create-project --prefer-dist laravel/laravel="8.*" "FAC Demo"
    ```

2. **Navigate to the project directory**:

    ```bash
    cd "FAC Demo"
    ```

3. **Install the `cloudcogsio/omnipay-firstatlanticcommerce-gateway` package**:

    ```bash
    composer require cloudcogsio/omnipay-firstatlanticcommerce-gateway
    ```

2024-11-08 16:45 UTC, cloudcogsio commented on src/FACGateway.php
> -        $this->setReturnUrl($url);
Add return here

2024-11-08 16:46 UTC, cloudcogsio commented on src/FACGateway.php
>          return $this->setParameter(Constants::CONFIG_KEY_MERCHANT_RESPONSE_URL, $url);
Remove

2024-11-08 16:54 UTC, cloudcogsio requested changes
In `setMerchantResponseURL`, remove
`return $this->setParameter(Constants::CONFIG_KEY_MERCHANT_RESPONSE_URL, $url);`
and add
`return $this->setReturnUrl($url);`

Then in `setReturnUrl`, add
`$this->setParameter(Constants::CONFIG_KEY_MERCHANT_RESPONSE_URL, $url);` before the current `return` statement,

Both functions should look like,

```
public function setMerchantResponseURL($url)
    {
        return $this->setReturnUrl($url);
    }
```
```
public function setReturnUrl($url)
    {
        $this->setParameter(Constants::CONFIG_KEY_MERCHANT_RESPONSE_URL, $url);
        return $this->setParameter("returnUrl", $url);
    }
```

Let me know if that works in your project. You can make the changes and resubmit PR.

2024-11-11 21:15 UTC, cloudcogsio approved these changes

2024-11-11 21:16 UTC, merged